# Generated by Django 3.1.5 on 2021-01-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('student_name', models.CharField(max_length=50)),
                ('student_dob', models.DateField()),
                ('student_qualification', models.CharField(max_length=15)),
                ('student_gender', models.CharField(max_length=10)),
            ],
        ),
    ]
