# Generated by Django 3.1.5 on 2021-01-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_universitydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('uni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.universitydetail')),
            ],
        ),
    ]
