# Generated by Django 3.1.5 on 2021-01-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebApp.coursename')),
                ('course_type', models.CharField(max_length=20)),
                ('course_duration', models.FloatField()),
                ('course_tuition', models.IntegerField()),
            ],
        ),
    ]
