# Generated by Django 3.1.5 on 2021-01-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_coursedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetail',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_status', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.coursename')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.studentdetail')),
                ('uni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.universitydetail')),
            ],
        ),
    ]
