# Generated by Django 3.1.5 on 2021-01-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_applicationdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='course_id',
            new_name='detail_id',
        ),
    ]
