# Generated by Django 3.1.5 on 2021-01-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20210116_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationDetail',
        ),
    ]
